version : '3'
services:
    web:
     build:
        context: ./
        dockerfile: docker/node/Dockerfile
     container_name: node_server
     volumes:
         - ./src/:/usr/src/app
         - node_modules:/usr/src/app/node_modules
     expose: [8080]
     ports:
         - '8080:8000'
    db:
      image: mongo:3.6
      container_name: mongo_db
      volumes:
          - dbdata:/data/db
      ports:
          - '27017:27017'
volumes:
    node_modules:
    dbdata:
