version : '3'
services:
    web:
     build:
        context: ./
        dockerfile: docker/node/Dockerfile
     container_name: node_server
     volumes:
         - ./src/:/usr/src/app
         - node_modules:/usr/src/app/node_modules
     expose: [8080]
     ports:
         - '8080:8000'
volumes:
    node_modules:
